version: '3.8'

services:
  db:
    image: postgres:15
    container_name: opsflow_db
    environment:
      POSTGRES_USER: opsflow
      POSTGRES_PASSWORD: opsflow123
      POSTGRES_DB: opsflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U opsflow -d opsflow"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
